# Generated by Django 3.0.7 on 2020-06-12 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('author', models.CharField(max_length=16, verbose_name='작성자')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
    ]
